name: GitHub metrics as SVG image
on:
  push:
    branches:
    - main
  schedule: [{cron: "0 22 * * *"}]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          # BASIC CONFIG --------------
          token: ${{ secrets.METRICS_TOKEN }}
          user: antopalla
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Rome
          output_action: commit
          committer_branch: metrics-renders
          committer_message: "chore: update metrics"
          # PLUGINS --------------
          plugin_languages: yes
          plugin_languages_categories: programming
          plugin_languages_colors: github
          plugin_languages_ignored: html, css
          plugin_languages_skipped: easymanage, uselesswebapp, procr
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: mastered
          plugin_topics_limit: 0
          plugin_gists: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_music: yes
          plugin_music_limit: 10
          plugin_music_playlist: https://open.spotify.com/playlist/1nsxKUMTNgUZ5KIbm38VPE?si=cf7379f2c9964c9e
